---

- name: Install Bindle dependencies
  sudo: True
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - liblz-dev
    - zlib1g-dev
    - samtools
    - libboost-filesystem1.48.0
    - libboost-program-options1.48.0
    - libboost-regex1.48.0
    - libboost-system1.48.0
    - libicu48
    - libxerces-c3.1
    - libxqilla6
    - gdebi
    - libxml-simple-perl
    - libcommon-sense-perl
    - libipc-system-simple-perl
    - libgetopt-euclid-perl
    - libfile-slurp-perl
    - libxml-dom-perl
    - libconfig-simple-perl
    - libdata-dump-perl
    - libcapture-tiny-perl
    - libcarp-always-perl
    - libjson-perl
    - libxml-libxml-perl
    - libxml-libxml-simple-perl
    - libdb4.8
    - libberkeleydb-perl
    - libtemplate-perl

- name: Download GeneTorrent (common)
  get_url:
    dest=/tmp
    url=http://cghub.ucsc.edu/software/downloads/GeneTorrent/3.8.5/genetorrent-common_3.8.5-ubuntu2.91-12.04_amd64.deb 

- name: Download GeneTorrent (download)
  get_url:
    dest=/tmp
    url=http://cghub.ucsc.edu/software/downloads/GeneTorrent/3.8.5/genetorrent-download_3.8.5-ubuntu2.91-12.04_amd64.deb

- name: Download GeneTorrent (upload)
  get_url:
    dest=/tmp
    url=http://cghub.ucsc.edu/software/downloads/GeneTorrent/3.8.5/genetorrent-upload_3.8.5-ubuntu2.91-12.04_amd64.deb

- Name: Install GeneTorrent 
  command: gdebi --n /tmp/genetorrent-common_3.8.5-ubuntu2.91-12.04_amd64.deb /tmp/genetorrent-download_3.8.5-ubuntu2.91-12.04_amd64.deb /tmp/genetorrent-upload_3.8.5-ubuntu2.91-12.04_amd64.deb
  sudo: True

- Name: Download Oracle Java
  dest=/tmp
  get_url: http://archive.cloudera.com/cm5/ubuntu/lucid/amd64/cm/pool/contrib/o/oracle-j2sdk1.7/oracle-j2sdk1.7_1.7.0+update25-1_amd64.deb
  
- Name: Install Oracle Java
  command: dpebi -i /tmp/oracle-j2sdk1.7_1.7.0+update25-1_amd64.deb

- Name: Update Alternatvies (install)
  command: update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-7-oracle-cloudera/jre/bin/java 2000
  sudo: True
 
- name: Update Alterantives (set)
  command: update-alternatives --set java /usr/lib/jvm/java-7-oracle-cloudera/jre/bin/java 

- name: Set Jave Environment Variable for Java
  command: echo 'JAVA_HOME=/usr/lib/jvm/java-7-oracle-cloudera' | tee -a /etc/environment
  sudo: True
