#!/usr/bin/env bash
set -e

## Installing all dependencies

sudo apt-get update

# apt-get general packages
sudo apt-get -q -y --force-yes install liblz-dev zlib1g-dev samtools libboost-filesystem1.48.0 \
libboost-program-options1.48.0 libboost-regex1.48.0 libboost-system1.48.0 libicu48 libxerces-c3.1 \
libxqilla6 gdebi libxml-simple-perl

# apt-get perl packages
sudo apt-get -q -y --force-yes install libcommon-sense-perl libipc-system-simple-perl \
libgetopt-euclid-perl libfile-slurp-perl libxml-dom-perl libconfig-simple-perl libdata-dump-perl \
libcapture-tiny-perl libcarp-always-perl libjson-perl libxml-libxml-perl libxml-libxml-simple-perl \
libdb4.8 libberkeleydb-perl libtemplate-perl

# Install GeneTorrent
wget --no-clobber http://cghub.ucsc.edu/software/downloads/GeneTorrent/3.8.5/genetorrent-common_3.8.5-ubuntu2.91-12.04_amd64.deb -P /tmp
wget --no-clobber http://cghub.ucsc.edu/software/downloads/GeneTorrent/3.8.5/genetorrent-download_3.8.5-ubuntu2.91-12.04_amd64.deb -P /tmp
wget --no-clobber http://cghub.ucsc.edu/software/downloads/GeneTorrent/3.8.5/genetorrent-upload_3.8.5-ubuntu2.91-12.04_amd64.deb  -P /tmp
sudo gdebi --n /tmp/genetorrent-common_3.8.5-ubuntu2.91-12.04_amd64.deb /tmp/genetorrent-download_3.8.5-ubuntu2.91-12.04_amd64.deb /tmp/genetorrent-upload_3.8.5-ubuntu2.91-12.04_amd64.deb

# install Oracle Java which is needed for SeqWare
wget http://archive.cloudera.com/cm5/ubuntu/lucid/amd64/cm/pool/contrib/o/oracle-j2sdk1.7/oracle-j2sdk1.7_1.7.0+update25-1_amd64.deb
dpkg -i oracle-j2sdk1.7_1.7.0+update25-1_amd64.deb

# cloudera 1.7 java package doesn't set up alternatives for some reason
update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-7-oracle-cloudera/jre/bin/java 2000
update-alternatives --set java /usr/lib/jvm/java-7-oracle-cloudera/jre/bin/java
echo 'JAVA_HOME=/usr/lib/jvm/java-7-oracle-cloudera' | sudo tee -a /etc/environment

# Install Seqware
wget https://github.com/SeqWare/seqware/releases/download/1.1.0-alpha.5/seqware -P /tmp
sudo cp /tmp/seqware /usr/local/bin/
sudo chmod a+x /usr/local/bin/seqware
